### ISSUE TITLE
"Oppdatert" podcast feed URL doesn't work

### ISSUE THREAD

**Issue by vebjornjr** [olaven/nrss#35]
I discovered today that the Oppdatert URL doesn't work and from my podcast app it seems it hasn't worked for the last week.
Cast Feed Validator confirms the problem. Others podcasts seems to work fine.

https://www.castfeedvalidator.com/validate.php?url=https://nrss.deno.dev/api/feeds/oppdatert

**Comment by timharek** [comment]
I see that it doesn't work when you navigate directly to the URL either: 
<https://nrss.deno.dev/api/feeds/oppdatert>

And I cannot reproduce locally, I guess @olaven has to check the logs to see what is the issue.

**Comment by olaven** [comment]
@vebjornjr @timharek thank you both for reporting and contributing! I'm adding this to my schedule.
