### ISSUE TITLE
gPodder 3.11.1 | Could not parse feed: <unknown>:1:196: not well-formed (invalid token)

### ISSUE THREAD

**Issue by tordenflesk** [olaven/NRSS#6]
```
https://nrss.deno.dev/api/feeds/berrum_beyer_snakker_om_greier:
Could not parse feed: https://nrss.deno.dev/api/feeds/berrum_beyer_snakker_om_greier: <unknown>:1:196: not well-formed (invalid token)
```

**Comment by olaven** [comment]
Takk for rapportering, @tordenflesk! Jeg får reprodusert dette og skal ta en kikk.

**Comment by olaven** [comment]
@tordenflesk Siste versjon skal fungere. Jeg testet nettopp med gPodder og fikk til å legge inn https://nrss.deno.dev/api/feeds/berrum_beyer_snakker_om_greier 👍
